/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SecretVoteBoxInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createPoll"
      | "endPoll"
      | "getEncryptedVoteCount"
      | "getPoll"
      | "getPollCount"
      | "hasVoted"
      | "pollCount"
      | "polls"
      | "protocolId"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PollCreated" | "PollEnded" | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createPoll",
    values: [string, string, string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endPoll",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedVoteCount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoll",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPollCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pollCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "polls", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "createPoll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endPoll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedVoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPoll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPollCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pollCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "polls", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace PollCreatedEvent {
  export type InputTuple = [
    pollId: BigNumberish,
    creator: AddressLike,
    title: string,
    expireAt: BigNumberish
  ];
  export type OutputTuple = [
    pollId: bigint,
    creator: string,
    title: string,
    expireAt: bigint
  ];
  export interface OutputObject {
    pollId: bigint;
    creator: string;
    title: string;
    expireAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PollEndedEvent {
  export type InputTuple = [pollId: BigNumberish];
  export type OutputTuple = [pollId: bigint];
  export interface OutputObject {
    pollId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [pollId: BigNumberish, voter: AddressLike];
  export type OutputTuple = [pollId: bigint, voter: string];
  export interface OutputObject {
    pollId: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecretVoteBox extends BaseContract {
  connect(runner?: ContractRunner | null): SecretVoteBox;
  waitForDeployment(): Promise<this>;

  interface: SecretVoteBoxInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPoll: TypedContractMethod<
    [
      title: string,
      description: string,
      options: string[],
      expireAt: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  endPoll: TypedContractMethod<[pollId: BigNumberish], [void], "nonpayable">;

  getEncryptedVoteCount: TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BigNumberish],
    [string],
    "view"
  >;

  getPoll: TypedContractMethod<
    [pollId: BigNumberish],
    [
      [string, string, string[], bigint, string, boolean] & {
        title: string;
        description: string;
        options: string[];
        expireAt: bigint;
        creator: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getPollCount: TypedContractMethod<[], [bigint], "view">;

  hasVoted: TypedContractMethod<
    [pollId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;

  pollCount: TypedContractMethod<[], [bigint], "view">;

  polls: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        title: string;
        description: string;
        expireAt: bigint;
        creator: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  vote: TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPoll"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      options: string[],
      expireAt: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "endPoll"
  ): TypedContractMethod<[pollId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedVoteCount"
  ): TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoll"
  ): TypedContractMethod<
    [pollId: BigNumberish],
    [
      [string, string, string[], bigint, string, boolean] & {
        title: string;
        description: string;
        options: string[];
        expireAt: bigint;
        creator: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPollCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [pollId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pollCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "polls"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        title: string;
        description: string;
        expireAt: bigint;
        creator: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [pollId: BigNumberish, optionIndex: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PollCreated"
  ): TypedContractEvent<
    PollCreatedEvent.InputTuple,
    PollCreatedEvent.OutputTuple,
    PollCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PollEnded"
  ): TypedContractEvent<
    PollEndedEvent.InputTuple,
    PollEndedEvent.OutputTuple,
    PollEndedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "PollCreated(uint256,address,string,uint256)": TypedContractEvent<
      PollCreatedEvent.InputTuple,
      PollCreatedEvent.OutputTuple,
      PollCreatedEvent.OutputObject
    >;
    PollCreated: TypedContractEvent<
      PollCreatedEvent.InputTuple,
      PollCreatedEvent.OutputTuple,
      PollCreatedEvent.OutputObject
    >;

    "PollEnded(uint256)": TypedContractEvent<
      PollEndedEvent.InputTuple,
      PollEndedEvent.OutputTuple,
      PollEndedEvent.OutputObject
    >;
    PollEnded: TypedContractEvent<
      PollEndedEvent.InputTuple,
      PollEndedEvent.OutputTuple,
      PollEndedEvent.OutputObject
    >;

    "VoteCast(uint256,address)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
